fix debit assistent error missing ceres plugin
plentymarkets/plugin-payment-debit pull request #5
Opened 2019-06-18 07:59 UTC by MKanitz

https://plentymarkets.kanbanize.com/ctrl_board/50/cards/64024/details/
@plentymarkets/team-order-payment 

Unklare Fehlermeldung bezüglich fehlendem Ceres Plugin wurde entfernt.
Zusätzlich hat dem Assistent noch der korrekte Bereich und die Kurzbeschreibung gefehlt.

2019-06-18 13:06 UTC, MaselP approved these changes
💎

2019-06-21 07:32 UTC, DDBreidenbach requested changes

2019-06-21 07:32 UTC, DDBreidenbach commented on resources/lang/en/debitAssistant.properties
> +assistantShortDescription = Assistant for setting up payment method debit
```suggestion
assistantShortDescription = Assistant for setting up the payment method debit
```

2019-06-24 08:17 UTC, DDBreidenbach commented on meta/documents/changelog_de.md
> +- Beim Abschließen des Assistenten, ohne aktives Ceres Plugin, konnte es zu Fehlern kommen. Dies wurde behoben.
```suggestion
- Beim Abschließen des Assistenten ohne aktives Ceres Plugin konnte es zu Fehlern kommen. Dies wurde behoben.
```

2019-06-24 08:17 UTC, DDBreidenbach commented on meta/documents/changelog_en.md
> +- An error when saving the assistant without active ceres plugin has been fixed.
```suggestion
- An error when saving the assistant without an active Ceres plugin has been fixed.
```

2019-06-25 08:34 UTC, DDBreidenbach approved these changes

2019-06-27 10:58 UTC, merged